### ISSUE TITLE
Not work with FIrebug 1.8

### ISSUE THREAD

**Issue by lilydjwg** [robnyman/firefinder#1]
On clicking `Filter` button, nothing happens except an error printed to the error console:

```
Error： FirebugContext is not defined
Source file：chrome://firefinder/content/firebug.js
Line：138
```

**Comment by robnyman** [comment]
Thanks, I've seen problems with it and will look into it as soon as I get the time.

**Comment by robnyman** [comment]
Finally fixed this issue, and working code committed here. I've submitted it for review by Mozilla, and as soon as it has gone through that, it will be available at https://addons.mozilla.org/en-US/firefox/addon/firefinder-for-firebug/
