### ISSUE TITLE
Firefinder not working in Firefox 33

### ISSUE THREAD

**Issue by nikorgl** [robnyman/firefinder#6]
There is no Firefinder tab in Firebug

**Comment by robnyman** [comment]
I just tested it and it showed up and worked well. Please make sure that you have the latest version of Firebug as well, if the problem comes from there.

**Comment by jbusam** [comment]
same issue for me... FF 33.1.1 on OSX with Firebug 2.0.6

**Comment by nikorgl** [comment]
I found out this bug turns up with mitro extension (https://www.mitro.co/)

**Comment by jbusam** [comment]
not using that extension, but I started to disable all extensions (not many anyhow)... turns out that it conflicts with 'Google Translate It'

**Comment by robnyman** [comment]
@jbusam @olimpbarnaul Sorry about that conflict. There is no way to protect keyboard shortcuts colloding. However, it _should_ show up if you choose it from the top menu, or open Firebug. If not, I'm not sure why another extension would block out an add-on to Firebug.
